# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: True
  config:
    entity: sungmin00-gwangju-institute-of-science-and-technology
    project: lewm_pusht
    name: lewm_${now:%Y%m%dT%H%M%S}
    id: ${checkpoint.data}_${checkpoint.model}_${now:%Y%m%dT%H%M%S}_${seed}
    save_dir: ${hydra:runtime.output_dir}
    resume: allow
    log_model: False
