# @package _global_
defaults:
  - /train@_global_: lewm
  - /preflight: default
  - _self_

task: train
project: lewm_pusht
gpu: 0
seed: 3072
dry_run: false

storage_root: /data/sungmin/lewm
checkpoint:
  data: pusht
  model: lewm
  final_name: lewm_retrain
  every_n_epochs: 1

subdir: ${checkpoint.data}/${checkpoint.model}/${now:%Y%m%dT%H%M%S}/${seed}

hydra:
  run:
    dir: /data/sungmin/lewm/runs/${project}/${now:%Y%m%dT%H%M%S}_${task}_seed${seed}
  job:
    name: ${project}_${task}
  output_subdir: hydra
